name: CI – AutoNote

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name:  Docker build 
        run: docker build -t autonote-api .

      - name:  Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name:  Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name:  Run tests with coverage
        run: pytest --cov=app --cov-report=term-missing 

      - name:  Lint (ruff)
        run: ruff check . --output-format=github

      - name:  Bandit (security)
        run: bandit -r app/

      - name:  pip-audit (dependency check)
        run: pip-audit
